var locationDatabase = function () {
  return ["AMSTERDAM", "ANKARA", "ALGIERS", "ACCRA", "AMMAN", "ATHENS", "BAGHDAD", "BANGKOK", "BEIJING", "BEIRUT", "BERLIN", "BERN", "BELGRADE", "BOGOTA", "BRATISLAVA", "BRASILIA", "BRUSSELS", "BUCHAREST", "BUDAPEST", "CAIRO", "CANBERRA", "CARACAS", "COPENHAGEN", "DHAKA", "DJIBOUTI", "DAMASCUS", "DOHA", "DUBLIN", "GIBRALTAR", "HANOI", "HAVANA", "HELSINKI", "ISLAMABAD", "JAKARTA", "JERUSALEM", "KABUL", "KATHMANDU", "KIEV", "KINGSTON", "LIMA", "LISBON", "LONDON", "LUXEMBOURG", "MADRID", "MANAGUA", "MANILA", "MINSK", "MONTEVIDEO", "MONACO", "MOSCOW", "NAIROBI", "NASSAU", "OSLO", "OTTAWA", "PARIS", "PRAGUE", "PRETORIA", "QUITO", "REYKJAVIK", "RIYADH", "ROME", "SANTIAGO", "SEOUL", "SINGAPORE", "STOLKHOLM", "TAIPEI", "TEHRAN", "TOKYO", "TRIPOLI", "VIENNA", "VIENTIANE", "WARSAW", "WASHINGTON", "WELLINGTON"];
};

var locationDatabase2 = function () {
  return ["MAUI", "SANTORINI", "BALI", "MAURITIUS", "FIJI", "CANCUN", "BARBADOS", "MALDIVES", "MARBELLA", "ANTIGUA", "MEXICO", "CANNES", "NICE", "MARBELLA", "IBIZA", "CRETE", "JAMAICA", "MYKONOS", "ARUBA", "BAHAMAS", "MIAMI", "BERMUDA", "SEYCHELLES", "SARDINIA", "ANGUILLA", "RIO", "CAIRNS", "CUBA", "GALAPAGOS", "PHUKET", "BORNEO", "CAPETOWN", "QUEENSTOWN", "PANAMA", "CROATIA", "BELIZE", "BORACAY", "KRABI", "HAWAII", "DUBAI", "SICILY", "MADAGASCAR" ,"KRABI"];
};

var locationDatabase3 = function () {
  return ["ATLANTIC", "SOUTHERN", "PACIFIC", "ARCTIC", "INDIAN", "MEDITERRANEAN", "BARBADOS", "CARIBBEAN", "ADRIATIC", "AEGEAN", "ANDAMAN", "BLACK", "BALTIC", "NORTH", "CELTIC", "CORAL", "DEAD", "CASPIAN", "JAVA", "ARABIAN", "RED", "NORTH", "NORWEGIAN", "AMAZON", "BOSPHORUS", "COLORADO", "CONGO", "DANUBE", "DELAWARE", "COMO", "GANGES", "GREAT", "HUDSON", "ERIE", "GENEVA", "GEORGE", "MICHIGAN", "ONTARIO", "TAHOE", "MEKONG", "MISSISSIPPI" ,"NILE", "RHINE", "SALT", "SEINE", "SEVEN", "THAMES", "YELLOW"];
};
